export const COLORS = {
  gradient1: '#C64998',
  gradient2: '#661348',
  primary: '#2E303A',
  black: '#000000',
  skyBlue: '#1877F2',
  borderColor: '#2E303A',
  fieldColor: '#F2F2F2',
  fieldBorder: '#DEDEDE',
  placeholder: 'rgba(0,0,0,0.5)',
  inputColor: '#1D211E',
  focused: '#373A46',
  white: '#FFFFFF',
  icon: '#1F1F1F',
  lightGrey: '#8C8C8C',
  lightWhite: '#EEEEEE',
  green: '#0A8B65',
  pink: '#B14088',
  grey: '#1D1D1D',
  switch: '#E6E6E6EE',
  dropDown: '#E0E0E0',
  radio: '#DCDCDC',
  radio2: '##F9F9F9',
  pink2: '#FF0069',
  grey3: '#696B74',
  yellow: '#FFCB4C',
  offWhite: '#FBFAF9',
  grey4: '#696969',
  grey5: '#82848C',
  green2: '#40C3B1',
  pink3: '#BF5A9E',
  purple: '#8D5BB7',
  PURPLE2: '#7B4CCB',
  white2: '#ECE1FF',
  offWhite2: '#F7F0E1',
  tab: '#F6F6F6',
  tbText: '#151515',
  search: '#9C9EA6',
  red : "#B5000C"
};

export const IMAGES = {
  logo: require('../assets/images/logo.png'),
  onBoarding: require('../assets/images/onBoarding.png'),
  headline: require('../assets/images/headline.png'),
  profile: require('../assets/images/profile.png'),
  background: require('../assets/images/background.png'),
  group: require('../assets/images/group.png'),
  contacts: require('../assets/images/contacts.png'),
  profile1: require('../assets/images/profile1.png'),
  profile2: require('../assets/images/profile2.png'),
  chat: require('../assets/images/chat.png'),
  chatProfile: require('../assets/images/chatProfile.png'),
  customProfile: require('../assets/images/img3.jpg'),
  groupDetail: require('../assets/images/group-detail.png'),
  single: require('../assets/images/signle.png'),
};

export const ICONS = {
  facebook: require('../assets/icons/facebook.png'),
  apple: require('../assets/icons/ios.png'),
  google: require('../assets/icons/google.png'),
  user: require('../assets/icons/user.png'),
  edit: require('../assets/icons/edit.png'),
  location: require('../assets/icons/location.png'),
  user2: require('../assets/icons/user-2.png'),
  bars: require('../assets/icons/bars.png'),
  globe: require('../assets/icons/globe.png'),
  phone: require('../assets/icons/phone.png'),
  insta: require('../assets/icons/insta.png'),
  tiktok: require('../assets/icons/tiktok.png'),
  tab1: require('../assets/icons/tab1.png'),
  tab2: require('../assets/icons/tab2.png'),
  tab3: require('../assets/icons/tab3.png'),
  tab4: require('../assets/icons/tab4.png'),
  vector: require('../assets/icons/Vector.png'),
  border: require('../assets/icons/border.png'),
  group: require('../assets/icons/group.png'),
  uncheck: require('../assets/icons/uncheck.png'),
  checked: require('../assets/icons/checked.png'),
  send: require('../assets/icons/send.png'),
  link: require('../assets/icons/link.png'),
  plus: require('../assets/icons/plus.png'),
  plus2: require('../assets/icons/plus2.png'),
  corner: require('../assets/icons/corner.png'),
  corner2: require('../assets/icons/left.png'),
  trash: require('../assets/icons/trash.png'),
  settings: require('../assets/icons/settings-2.png'),
  cross: require('../assets/icons/x.png'),
  mute: require('../assets/icons/mute.png'),
  mute2: require('../assets/icons/mute2.png'),
  add: require('../assets/icons/user3.png'),
  calender: require('../assets/icons/calender.png'),
  user4: require('../assets/icons/user4.png'),
  download: require('../assets/icons/download.png'),
  user5: require('../assets/icons/user5.png'),
  send2: require('../assets/icons/send2.png'),
  pen: require('../assets/icons/Pen.png'),
};

export const FONTS = {
  headline: 'Caprasimo-Regular',
  regular: 'SplineSans-Regular',
  medium: 'SplineSans-Medium',
  semiBold: 'SplineSans-SemiBold',
  bold: 'SplineSans-Bold',
  regular2: 'PublicSans-Regular',
  medium2: 'PublicSans-Medium',
  semiBold2: 'PublicSans-SemiBold',
  bold2: 'PublicSans-Bold',
  tab: 'SchibstedGrotesk-SemiBold',
  stylish: 'ShadowsIntoLight-Regular',
};
