export const COLORS = {
  gradient1: '#C64998',
  gradient2: '#661348',
  primary: '#2E303A',
  black: '#000000',
  skyBlue: '#1877F2',
  borderColor: '#2E303A',
  fieldColor: '#F2F2F2',
  fieldBorder: '#DEDEDE',
  placeholder: 'rgba(0,0,0,0.5)',
  inputColor: '#1D211E',
  focused: '#373A46',
  white: '#FFFFFF',
  icon: '#1F1F1F',
  lightGrey: '#8C8C8C',
  lightWhite: '#EEEEEE',
  green: '#0A8B65',
  pink: '#B14088',
  grey: '#1D1D1D',
  switch: '#E6E6E6EE',
  dropDown: '#E0E0E0',
  radio: '#DCDCDC',
  radio2: '##F9F9F9',
  pink2: '#FF0069',
  grey3: '#696B74',
};

export const IMAGES = {
  logo: require('../assets/images/logo.png'),
  onBoarding: require('../assets/images/onBoarding.png'),
  headline: require('../assets/images/headline.png'),
  profile: require('../assets/images/profile.png'),
  background: require('../assets/images/background.png'),
  group: require('../assets/images/group.png'),
  contacts: require('../assets/images/contacts.png'),
};

export const ICONS = {
  facebook: require('../assets/icons/facebook.png'),
  apple: require('../assets/icons/ios.png'),
  google: require('../assets/icons/google.png'),
  user: require('../assets/icons/user.png'),
  edit: require('../assets/icons/edit.png'),
  location: require('../assets/icons/location.png'),
  user2: require('../assets/icons/user-2.png'),
  bars: require('../assets/icons/bars.png'),
  globe: require('../assets/icons/globe.png'),
  phone: require('../assets/icons/phone.png'),
  insta: require('../assets/icons/insta.png'),
  tiktok: require('../assets/icons/tiktok.png'),
  tab1: require('../assets/icons/tab1.png'),
  tab2: require('../assets/icons/tab2.png'),
  tab3: require('../assets/icons/tab3.png'),
  tab4: require('../assets/icons/tab4.png'),
  vector: require('../assets/icons/Vector.png'),
  border: require('../assets/icons/border.png'),
  group: require('../assets/icons/group.png'),
};

export const FONTS = {
  headline: 'Caprasimo-Regular',
  regular: 'SplineSans-Regular',
  medium: 'SplineSans-Medium',
  semiBold: 'SplineSans-SemiBold',
  bold: 'SplineSans-Bold',
  regular2: 'PublicSans-Regular',
  medium2: 'PublicSans-Medium',
  semiBold2: 'PublicSans-SemiBold',
  bold2: 'PublicSans-Bold',
  tab: 'SchibstedGrotesk-SemiBold',
  stylish: 'ShadowsIntoLight-Regular',
};
